name: Deployment

on:
  push:
    branches:
      - main  
  workflow_dispatch:
    
env:
  SRC_DIR: ./
  SRC_FILE: resume.tex

jobs: 
  build: 
   runs-on: ubuntu-latest 
   steps: 
    - name: Set up Git repository
      uses: actions/checkout@v2 
    - name: Install Pandoc and build HTML
      run: |
        sudo apt install pandoc 
        sudo pandoc --toc resume.tex -s --mathjax -o resume.html

    - name: Publish the web pages 
      uses:  peaceiris/actions-gh-pages@v3 
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }} 
        publish_dir: ./ 
  
