name: Deployment

on:
  push:
    branches:
      - main  
  workflow_dispatch:
    
env:
  SRC_DIR: ./
  SRC_FILE: resume.tex

jobs: 
  deploy: 
   runs-on: ubuntu-latest 
   steps: 
    - name: Set up Git repository
      uses: actions/checkout@v2 
    - name: Install Pandoc and build HTML
      run: |
        sudo apt install pandoc 
        mkdir -p pages
        sudo pandoc --toc resume.tex -s --mathjax -o ./pages/index.html
      

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: pages
        repositorty-name: ehsan2754/resume
        target-folder: public
